/**
 * Antifactoring App
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("InvoicesApi", () => {
  let instance: api.InvoicesApi
  beforeEach(function() {
    instance = new api.InvoicesApi(config)
  });

  test("scanInvoice", () => {
    const file: any = undefined
    const apiKey: any = undefined
    return expect(instance.scanInvoice(file, apiKey, {})).resolves.toBe(null)
  })
})

